### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LiteEagle262** [htach/roliwrapper#1]
C:\Users\admin\Downloads>python main.py
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\main.py", line 1, in <module>
    import roliwrapper
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\roliwrapper\__init__.py", line 1, in <module>
    from roliwrapper.itemapi import ItemCache
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\roliwrapper\itemapi.py", line 15, in <module>
    class ItemCache:
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\roliwrapper\itemapi.py", line 31, in ItemCache
    def __getitem__(cls, identifier: int | str) -> Item:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by htach** [comment]
was using a 3.10 feature but i've changed it back so older versions of python can be used
